version: '3.8'
services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    # user: "101:101"
    container_name: clickhouse-01
    hostname: clickhouse-01
    networks:
      force_cluster:
        ipv4_address: 192.168.8.1
    volumes:
      - ${PWD}/fs/volumes/server/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/server/config/remote_server.xml:/etc/clickhouse-server/config.d/remote_server.xml
      - ${PWD}/fs/volumes/server/config/user-keeper.xml:/etc/clickhouse-server/config.d/user-keeper.xml
      - clickhouse-data-01:/var/lib/clickhouse/
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    # user: "101:101"
    container_name: clickhouse-02
    hostname: clickhouse-02
    networks:
      force_cluster:
        ipv4_address: 192.168.8.2
    volumes:
      - ${PWD}/fs/volumes/server/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/server/config/remote_server.xml:/etc/clickhouse-server/config.d/remote_server.xml
      - ${PWD}/fs/volumes/server/config/user-keeper.xml:/etc/clickhouse-server/config.d/user-keeper.xml
      - clickhouse-data-02:/var/lib/clickhouse/
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-03:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    # user: "101:101"
    container_name: clickhouse-03
    hostname: clickhouse-03
    networks:
      force_cluster:
        ipv4_address: 192.168.8.3
    volumes:
      - ${PWD}/fs/volumes/server/clickhouse-03/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ${PWD}/fs/volumes/clickhouse-03/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/server/config/remote_server.xml:/etc/clickhouse-server/config.d/remote_server.xml
      - ${PWD}/fs/volumes/server/config/user-keeper.xml:/etc/clickhouse-server/config.d/user-keeper.xml
      - clickhouse-data-03:/var/lib/clickhouse/
    ports:
      - "8125:8123"
      - "9002:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-04:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    # user: "101:101"
    container_name: clickhouse-04
    hostname: clickhouse-04
    networks:
      force_cluster:
        ipv4_address: 192.168.8.4
    volumes:
      - ${PWD}/fs/volumes/server/clickhouse-04/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      # - ${PWD}/fs/volumes/clickhouse-04/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/server/config/remote_server.xml:/etc/clickhouse-server/config.d/remote_server.xml
      - ${PWD}/fs/volumes/server/config/user-keeper.xml:/etc/clickhouse-server/config.d/user-keeper.xml
      - clickhouse-data-04:/var/lib/clickhouse/
    ports:
      - "8126:8123"
      - "9003:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03

  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    # user: "101:101"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    networks:
      force_cluster:
        ipv4_address: 192.168.8.11
    volumes:
     - ${PWD}/fs/volumes/keeper/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "9181:9181"
  
  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    # user: "101:101"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    networks:
      force_cluster:
        ipv4_address: 192.168.8.12
    volumes:
     - ${PWD}/fs/volumes/keeper/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "9182:9181"
  
  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    # user: "101:101"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    networks:
      force_cluster:
        ipv4_address: 192.168.8.13
    volumes:
     - ${PWD}/fs/volumes/keeper/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "9183:9181"

networks:
  force_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.254

volumes:
  clickhouse-data-01:
  clickhouse-data-02:
  clickhouse-data-03:
  clickhouse-data-04:
