# 指定 pipeline，且由 docker runner 執行
kind: pipeline
type: docker
name: github-push-gitlab # 可自行定義的名稱

trigger:
  branch:
    - feature/drone # 指定觸發的 branch
  event:
    - push

platform:
  os: linux
  arch: arm64

steps:
  - name: dummy-step # 新增的假步驟
    image: alpine:latest # 使用輕量級的 alpine 映像
    commands:
      - echo "這是一個假的步驟，什麼都不做"

# mirror to gitlab
  - name: mirror to gitlab 
    image: alpine:latest
    environment:
      GITHUB_REPO: github.com/itmrchow/infra.git
      GITLAB_REPO: gitlab.com/jefftestmirror/infra2.git
      GITLAB_USERNAME: jeff.wu4
      GITLAB_ACCESS_TOKEN: glpat-PRWQvEbnTW1pajF_Hz2U
    commands:
      - echo [clone mirror start]
      - export GITHUB_REPO_URL=https://$GITHUB_REPO
      - export GITLAB_REPO_URL=https://$GITLAB_USERNAME:$GITLAB_ACCESS_TOKEN@$GITLAB_REPO
      - echo GITHUB_REPO_URL=$GITHUB_REPO_URL
      - echo GITLAB_REPO_URL=$GITLAB_REPO_URL
      - apk add git
      - git clone --bare $GITHUB_REPO_URL ./bare.git
      - cd ./bare.git
      - git remote add gitlab $GITLAB_REPO_URL
      - git push gitlab --mirror
      - echo [cloen mirror finish]
