version: '3.7'

services:
  redis_node1:
    image: redis:7
    container_name: redis_node1
    ports:
      - 7000:7000
      - 17000:17000
    # volumes:
    #   - ./conf:/etc/data/
    command: ["redis-server", "--port", "7000", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0" , "--cluster-announce-ip","192.168.8.24", "--cluster-announce-port", "7000", "--cluster-announce-bus-port", "17000"]
        
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7000", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30    
    networks:
      redis_network:
        ipv4_address: 172.28.0.2
  
  redis_node2:
    image: redis:7
    container_name: redis_node2
    ports:
      - "7001:7001"
      - 17001:17001
    # volumes:
    #   - ./conf:/etc/data
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0", "--cluster-announce-ip", "192.168.8.24", "--cluster-announce-port", "7001", "--cluster-announce-bus-port", "17001"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7001", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      redis_network:
        ipv4_address: 172.28.0.3

  redis_node3:
    image: redis:7
    container_name: redis_node3
    ports:
      - "7002:7002"
      - 17002:17002
    # volumes:
    #   - ./conf:/etc/data
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0", "--cluster-announce-ip", "192.168.8.24", "--cluster-announce-port", "7002", "--cluster-announce-bus-port", "17002"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7002", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30    
    networks:
      redis_network:
        ipv4_address: 172.28.0.4


  redis_node4:
    image: redis:7
    container_name: redis_node4
    ports:
      - "7003:7003"
      - 17003:17003
    # volumes:
    #   - ./conf:/etc/data
    command: ["redis-server", "--port", "7003", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0", "--cluster-announce-ip", "192.168.8.24", "--cluster-announce-port", "7003", "--cluster-announce-bus-port", "17003"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7003", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30    
    networks:
      redis_network:
        ipv4_address: 172.28.0.5

  redis_node5:
    image: redis:7
    container_name: redis_node5
    ports:
      - "7004:7004"
      - 17004:17004
    # volumes:
    #   - ./conf:/etc/data
    command: ["redis-server", "--port", "7004", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0", "--cluster-announce-ip", "192.168.8.24", "--cluster-announce-port", "7004", "--cluster-announce-bus-port", "17004"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7004", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30    
    networks:
      redis_network:
        ipv4_address: 172.28.0.6

  redis_node6:
    image: redis:7
    container_name: redis_node6
    ports:
      - "7005:7005"
      - 17005:17005
    # volumes:
    #   - ./conf:/etc/data
    command: ["redis-server", "--port", "7005", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "20000", "--appendonly", "yes", "--bind", "0.0.0.0", "--cluster-announce-ip", "192.168.8.24", "--cluster-announce-port", "7005", "--cluster-announce-bus-port", "17005"]
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "7005", "cluster", "info" ]
      interval: 1s
      timeout: 3s
      retries: 30    
    networks:
      redis_network:
        ipv4_address: 172.28.0.7

  # redis-cluster-creator:
  #   image: redis
  #   entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create 172.28.0.2:7000 172.28.0.3:7001 172.28.0.4:7002 172.28.0.5:7003 172.28.0.6:7004 172.28.0.7:7005 --cluster-replicas 1']
  #   networks:
  #     redis_network:    
  #   depends_on:
  #     redis_node1:
  #       condition: service_healthy
  #     redis_node2:
  #       condition: service_healthy
  #     redis_node3:
  #       condition: service_healthy
  #     redis_node4:
  #       condition: service_healthy
  #     redis_node5:
  #       condition: service_healthy
  #     redis_node6:
  #       condition: service_healthy

networks:
    redis_network:
      driver: bridge
      ipam:
        config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1